### ISSUE TITLE
the default version of the doc on RTD is 2.5

### ISSUE THREAD

**Issue by stof** [Behat/docs#50]
The default version is configured as being 2.5 currently, making `http://docs.behat.org` redirect to the 2.5 rather than the latest. Is it expected ?

**Comment by stof** [comment]
@everzet what is the reason for this choice. I got many complains about this

**Comment by everzet** [comment]
So that ReadTheDocs can automatically redirect people coming from old articles across the web for `/some-legacy-doc.html` to `v2.5/some-legacy-doc.html`. Otherwise we have a chance of people with valid links getting `404` :/

**Comment by yourwebmaker** [comment]
Same for http://behat.org and http://docs.behat.org/en/

Google's index is pointing to 2.5 as well.

![screen shot 2015-03-26 at 6 36 45 pm](https://cloud.githubusercontent.com/assets/812971/6857651/2dbf9f86-d3e7-11e4-8347-218deb73f337.png)

**Comment by wheelsandcogs** [comment]
Guys, I appreciate that documentation is a big job, but this will be adding a lot of confusion for anyone new to Behat. Is 3.x not recommended yet? If so, this should be made clear somewhere, otherwise the docs should default to the current recommended version.

If v3 is recommended but the docs aren't finished, then please still default to v3 docs and just have an obvious warning at the top of each page explaining that they're incomplete.

**Comment by m4grio** [comment]
+1
As a new behat adopter this issue made me lose tons of work hours dealing with outdated documentation that simply doesn't work with behat 3.x.

**Comment by theshaunwalker** [comment]
I just had a bunch of hassle regarding this too, until I finally noticed that you can switch the version via a tiny box in the bottom right of the screen.

If this can be changed in the readthedocs theme I'd highly recommend doing so, it needs to be a lot more prominent and towards the top of the page. It will save a lot of frustration and confusion.
