### ISSUE TITLE
Portuguese translation

### ISSUE THREAD

**Issue by eddiejaoude** [Behat/docs#69]
I might have a Portuguese resource, that could translate the documentation.

Would this be of benefit?

**Comment by stof** [comment]
We tried in the past to have a French version of the doc, but the issue is that translating the doc is not a one-shot task. It requires updating the translation each time changes are done in the English version and this often does not happen. And outdated translations are worse for the project than no translations.
Even the Symfony project is considering dropping the translated documentations from the official website because community-driven translations are not kept uptodate.

So I would be against providing the official documentation on the behat.org website itself. What do you think @everzet ?

**Comment by eddiejaoude** [comment]
Fair enough, it was just an idea :smile: 

Let me know

**Comment by everzet** [comment]
I agree with @stof

**Comment by eddiejaoude** [comment]
No worries. Thanks for clarifying
